services:
  server:
    container_name: testnet-moniswap-server
    networks:
      - testnet-dapp
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./server
      dockerfile: Dockerfile
  client:
    container_name: testnet-moniswap-client
    networks:
      - testnet-dapp
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./main
      dockerfile: Dockerfile
    environment:
      - NETWORK=testnet
  proxy:
    container_name: testnet-moniswap-proxy
    networks:
      - testnet-dapp
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5400:80
    depends_on:
      - client
      - server
networks:
  testnet-dapp:
    external: false
