version: "3.3"
services:
  server:
    container_name: testnet-moniswap-server
    networks:
      - testnet-dapp
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./server
      dockerfile: dockerfile
  client:
    container_name: testnet-moniswap-client
    networks:
      - testnet-dapp
    extra_hosts:
      - host.docker.internal:host-gateway
    build:
      context: ./main
      dockerfile: Dockerfile
    ports:
      - 5447:5447
    environment:
      - NETWORK=testnet
networks:
  testnet-dapp:
    external: false
