import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AllContexts from "@/contexts/all";
import Header from "@/ui/Header";
import Footer from "@/ui/Footer";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"]
});

export const metadata: Metadata = {
  title: "Moniswap | Liquidity hub on Berachain",
  description:
    "Moniswap: The central trading and liquidity marketplace on Berachain. Moniswap veNFTs votes on token emissions and receive incentives and fees generated by the protocol.",
  openGraph: {
    description:
      "Moniswap: The central trading and liquidity marketplace on Berachain. Moniswap veNFTs votes on token emissions and receive incentives and fees generated by the protocol.",
    title: "Moniswap | Liquidity hub on Berachain",
    tags: ["bera", "liquidity", "moniswap", "aggregator"]
  },
  twitter: {
    description:
      "Moniswap: The central trading and liquidity marketplace on Berachain. Moniswap veNFTs votes on token emissions and receive incentives and fees generated by the protocol.",
    title: "Moniswap | Liquidity hub on Berachain",
    card: "summary_large_image"
  }
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-black">
      <body className={inter.className}>
        <AllContexts>
          <div className="min-h-screen w-screen overflow-x-hidden flex flex-col justify-start items-center gap-5 bg-[#000004]">
            <Header />
            <div className="self-stretch overflow-auto mt-auto">{children}</div>
            <Footer />
          </div>
        </AllContexts>
      </body>
    </html>
  );
}
